swagger: '2.0'
info:
    title: arya-admin API
    description: A configurable mock server
    version: "0.1.0"
host: arya.guokr.cn
schemes:
    - http
basePath: /
consumes:
    - application/json
produces:
    - application/json
definitions:
    id:
        type: integer
        format: int32
    account_id:
        type: integer
        format: int32
    domain:
        type: string
        description: www domain
        minLength: 1
        maxLength: 256
    headers:
        type: string
        description: headers in json format
    body:
        type: string
        description: body in post, schema format
    options:
        type: object
        properties:
            delay:
                type: integer
                format: int32
                description: delay time in ms
                    
    url:
        type: string
        description: de facto limit of 2000 characters
        minLength: 1
        maxLength: 2000
    method:
        type: string
        description: http method, such as GET/POST/PUT etc.
        enum:
            - GET
            - POST
            - PUT
            - DELETE
    content_type:
        type: string
        description: body content type
        enum:
            - json
            - xml
            - raw
    Namespace:
        type: object
        properties:
            name:
                type: string
                description: namespace name
            ip_segment:
                type: string
                description: ip segment such as 10.0.80.9, 10.0.*.*
    Request:
        type: object
        properties:
            method:
                $ref: '#/definitions/method'
            path:
                $ref: '#/definitions/url'
            headers:
                $ref: '#/definitions/headers'
            body:
                $ref: '#/definitions/body'
            options:
                $ref: '#/definitions/options'
    Response:
        type: object
        properties:
            headers:
                $ref: '#/definitions/headers'
            body:
                $ref: '#/definitions/body'
            content_type:
                $ref: '#/definitions/content_type'
    Route:
        type: object
        properties:
            id:
                $ref: '#/definitions/id'
            request:
                $ref: '#/definitions/Request'
            responses:
                $ref: '#/definitions/Response'
    CreateRoute:
        type: object
        properties:
            request:
                $ref: '#/definitions/Request'
            responses:
                $ref: '#/definitions/Response'
    AppEnv:
        type: object
        properties:
            id:
                $ref: '#/definitions/id'
            namespace:
                $ref: '#/definitions/Namespace'
            routes:
                type: array
                items:
                    $ref: '#/definitions/Route'
    CreateAppEnv:
        type: object
        properties:
            namespace:
                $ref: '#/definitions/Namespace'
    Engine:
        type: object
        properties:
            status:
                type: string
                enum:
                    - active
                    - inactive
            message:
                type: string
                description: status detail
            report:
                type: string
                description: report in json format (return by engine)
            appenvs:
                type: array
                description: active appenvs (return by engine)
                items:
                    $ref: '#/definitions/AppEnv'
    OperateEngine:
        type: object
        properties:
            operate:
                type: string
                enum:
                    - start
                    - stop
                    - restart
            appenv_ids:
                type: array
                items:
                    $ref: '#/definitions/id'
    Error:
        properties:
            error_code:
                type: string
            message:
                type: string
            text:
                type: string
parameters:
    account_id_in_path:
        description: account id in path
        name: account_id
        in: path
        required: true
        type: integer
    appenv_id_in_path:
        description: appenv id in path
        name: appenv_id
        in: path
        required: true
        type: integer
    route_id_in_path:
        description: route id in path
        name: route_id
        in: path
        required: true
        type: integer
    account_id_in_query:
        description: account id in query
        name: account_id
        in: query
        required: false
        type: integer
    page:
        description: page number
        name: page
        in: query
        required: false
        type: integer
        format: int32
        maximum: 10000
    per_page:
        description: per_page number
        name: per_page
        in: query
        required: false
        type: integer
        format: int32
        maximum: 100
    offset:
        description: offset number
        name: offset
        in: query
        required: false
        format: int32
        type: integer
    limit:
        description: limit number
        name: limit
        in: query
        required: false
        type: integer
        format: int32
        maximum: 100
paths:
    /appenvs:
        get:
            summary: appenv list
            description: appenv list
            tags: [OPEN_ADMIN]
            operationId: get_appenvs
            parameters:
                - $ref: '#/parameters/offset'
                - $ref: '#/parameters/limit'
                - $ref: '#/parameters/page'
                - $ref: '#/parameters/per_page'
            responses:
                200:
                    description: Success
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/AppEnv'
                default:
                    description: Unexpected Error
                    schema:
                        $ref: '#/definitions/Error'
        post:
            summary: create appenv
            description: create appenv
            tags: [OPEN_ADMIN]
            operationId: post_appenvs
            parameters:
                - name: create_appenv
                  in: body
                  required: true
                  schema:
                      $ref: '#/definitions/CreateAppEnv'
            responses:
                201:
                    description: created appenv
                    schema:
                        $ref: '#/definitions/AppEnv'
                default:
                    description: Unexpected Error
                    schema:
                        $ref: '#/definitions/Error'
    /appenvs/{appenv_id}:
        get:
            summary: get appenv
            description: get appenv
            tags: [OPEN_ADMIN]
            operationId: get_appenvs_id
            parameters:
                - $ref: '#/parameters/appenv_id_in_path'
                - $ref: '#/parameters/offset'
                - $ref: '#/parameters/limit'
                - $ref: '#/parameters/page'
                - $ref: '#/parameters/per_page'
            responses:
                200:
                    description: Success
                    schema:
                        $ref: '#/definitions/AppEnv'
                default:
                    description: Unexpected Error
                    schema:
                        $ref: '#/definitions/Error'
    /appenvs/{appenv_id}/routes:
        get:
            summary: get routes of appenv
            description: get routes of appenv
            tags: [OPEN_ADMIN]
            operationId: get_appenv_id_routes
            parameters:
                - $ref: '#/parameters/appenv_id_in_path'
                - $ref: '#/parameters/offset'
                - $ref: '#/parameters/limit'
                - $ref: '#/parameters/page'
                - $ref: '#/parameters/per_page'
            responses:
                200:
                    description: Success
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Route'
                default:
                    description: Unexpected Error
                    schema:
                        $ref: '#/definitions/Error'
        post:
            summary: create route of appenv
            description: create route of appenv
            tags: [OPEN_ADMIN]
            operationId: post_appenv_id_routes
            parameters:
                - $ref: '#/parameters/appenv_id_in_path'
                - name: create_route
                  in: body
                  required: true
                  schema:
                      $ref: '#/definitions/CreateRoute'
            responses:
                201:
                    description: created route
                    schema:
                        $ref: '#/definitions/Route'
                default:
                    description: Unexpected Error
                    schema:
                        $ref: '#/definitions/Error'
    /appenvs/{appenv_id}/routes/{route_id}:
        get:
            summary: get route of appenv
            description: get route of appenv
            tags: [OPEN_ADMIN]
            operationId: get_appenv_id_routes_id
            parameters:
                - $ref: '#/parameters/appenv_id_in_path'
                - $ref: '#/parameters/route_id_in_path'
            responses:
                200:
                    description: Success
                    schema:
                        $ref: '#/definitions/Route'
                default:
                    description: Unexpected Error
                    schema:
                        $ref: '#/definitions/Error'
    /engine:
        get:
            summary: get engine status
            description: get engine status
            tags: [OPEN_ENGINE]
            operationId: get_engine
            responses:
                200:
                    description: Success
                    schema:
                        $ref: '#/definitions/Engine'
                default:
                    description: Unexpected Error
                    schema:
                        $ref: '#/definitions/Error'
        put:
            summary: start/stop/restart engine
            description: start/stop/restart engine
            tags: [OPEN_ENGINE]
            operationId: put_engine
            parameters:
                - name: put_engine
                  in: body
                  required: true
                  schema:
                      $ref: '#/definitions/OperateEngine'
            responses:
                200:
                    description: operation succeed
                    schema:
                        $ref: '#/definitions/Engine'
                default:
                    description: Unexpected Error
                    schema:
                        $ref: '#/definitions/Error'
tags:
    - {description: "配置管理", name: OPEN_ADMIN}
    - {description: "引擎控制", name: OPEN_ENGINE}
